# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  encoding: utf8
  database: demo_table
  pool: 5
  username: root
  password: 123456
  host: <%= ENV['DATABASE_HOST'].present? ? ENV['DATABASE_HOST'] : 'localhost' %>
  #socket: /tmp/mysql.sock